kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongocluster-role-binding
subjects:
- kind: ServiceAccount
  name: mongocluster-svc-account
  apiGroup: ""
roleRef:
  kind: Role
  name: mongocluster-role
  apiGroup: rbac.authorization.k8s.io