kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongocluster-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["statefulsets", "pods"]
  verbs: ["*"]
- apiGroups: ["adamtoy.io"]
  resources: ["mongoclusters"]
  verbs: ["watch"]